import type { Metadata } from "next";
import '@/app/styles/globals.css';
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {children: React.ReactNode};
export default function RootLayout({children}:Props) {
  return (
    <html lang="ko">
      <body>
        {children}
      </body>
    </html>
  );
}
