import type { Metadata } from "next";
import '@/app/styles/globals.css';
import * as style from '@/app/styles/component/layout.css';
import Header from "@/app/_component/Header";
import Nav from "@/app/_component/Nav";
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
import AuthProvider from "@/app/_lib/nextauth/index";
config.autoAddCss = false;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = { children: React.ReactNode };
export default function RootLayout({ children }: Props) {
  return (
    <html lang="ko">
      <body>
        <AuthProvider>
          <div className={style.Wrapper}>
            <Header />
            <div className={style.Container}>
              <Nav />
              {children}
            </div>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
